- name: "Install pyproxytools package : {{ pyproxy.package.version }}"
  ansible.builtin.pip:
    name: "pyproxytools{{ '==' + pyproxy.package.version if pyproxy.package.version != 'latest' else '' }}"
    state: present
