- name: Include install from source
  ansible.builtin.include_tasks: install_from_source.yml
  when: pyproxy.deploy_method == "source"

- name: Include install from docker
  ansible.builtin.include_tasks: install_from_docker.yml
  when: pyproxy.deploy_method == "docker"

- name: Include install from compose
  ansible.builtin.include_tasks: install_from_compose.yml
  when: pyproxy.deploy_method == "compose"

- name: Include install from package
  ansible.builtin.include_tasks: install_from_package.yml
  when: pyproxy.deploy_method == "package"
